version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/app/uploads
      - ./app/outputs:/app/outputs

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app